### ISSUE TITLE
readPixel returns 0

### ISSUE THREAD

**Issue by KrisKasprzak** [mjs513/ILI9488_t3#30]
I have a neat PrintScreen utility for the ILI9341_t3 and related displays where it captures the screen and saves to a BMP on and SD card. I'm hoping on getting this same capability for 3.5" ILI9488 displays. Note many of these displays don't have tri-state buffer on the MISO, but I've added an external buffer and it appears to allow MISO to operate properly. I have played with timings and I can get readPixel to work but at that cost of display operation. 

Here's the display I'm using https://www.amazon.com/FDSF-3-5Inch-480X320-ILI9488-Digital/dp/B09Z69LV5K/?_encoding=UTF8&pd_rd_w=q1p7G&content-id=amzn1.sym.8cf3b8ef-6a74-45dc-9f0d-6409eb523603&pf_rd_p=8cf3b8ef-6a74-45dc-9f0d-6409eb523603&pf_rd_r=GS07SXFEKAGSM3YM0B4G&pd_rd_wg=fQUfM&pd_rd_r=b0b40723-8c31-4d27-a19f-44c8306fd7bf&ref_=pd_gw_ci_mcx_mi

Any help is greatly appreciated.

Here's what I tried:

in the .h file 

// the following timings are used (display works, readPixel() does not
#elif defined(__IMXRT1052__) || defined(__IMXRT1062__)  // Teensy 4.x
	#define ILI9488_SPICLOCK       30000000
	#define ILI9488_SPICLOCK_READ   4000000

// If I change the timings to the values listed below, the display does not work but readPixel() does (weird).
#elif defined(__IMXRT1052__) || defined(__IMXRT1062__)  // Teensy 4.x
	#define ILI9488_SPICLOCK       30000000
	#define ILI9488_SPICLOCK_READ   4000000

Here is my test code:

#include <SPI.h>                 
#include <ILI9488_t3.h>   

// create display and DS objects
ILI9488_t3 Display = ILI9488_t3(10, 9, 8, 11, 13, 12);

void setup() {
  Serial.begin(115200);

  //#ifdef debug
  while ((!Serial) || (millis() > 5000)) {}
  //#endif

  Serial.println("Starting ");

  Display.begin();
  Display.setRotation(3);
  delay(100);

  Display.fillScreen(0);
  Display.fillRect(50, 50, 50, 50, 332);

  Display.drawPixel(10, 10, 332);
  delay(100);
  Serial.print("readPixel "); Serial.println(Display.readPixel(10, 10));
// should report 332 as the color of pixel 10,10

}

/*

  main loop function

*/

void loop() {

}

**Comment by mjs513** [comment]
Hi Kris
Think there is another way without using the buffer - I used it but off the
top of my head I forgot what I did - have to go look it up again.  Funny I
was just thinking about this last night as well.  Stay tuned.

**Comment by mjs513** [comment]
@KrisKasprzak 
Ok found what I did for the ILI9341 using KurtE's version of the library (pretty close to the way each works).  Basically what I did was put the Touch_CS pin high.  Here is a little test sketch I wrote to verify readRect was working:
```
#include <ILI9341_t3n.h>

#define TFT_DC  9
#define TFT_CS 10
#define TFT_RST 8
#define TOUCH_CS 27
ILI9341_t3n tft = ILI9341_t3n(TFT_CS, TFT_DC, TFT_RST);

void setup() {
  **pinMode(TOUCH_CS, OUTPUT);
  digitalWrite(TOUCH_CS, HIGH);**
  
  tft.begin();
  tft.fillWindow(ILI9341_BLACK);

  tft.setTextColor(ILI9341_WHITE);
  tft.setTextSize(2);
  tft.println(F("Waiting for Arduino Serial Monitor..."));
  while (!Serial) {
    if (millis() > 3000) break;
  }
  Serial.printf("\nScreen Width: %u Height: %d\n", tft.width(), tft.height());

  uint8_t r, g, b;
  //tft.useFrameBuffer(true);
  //tft.fillWindow(ILI9341_RED);
  tft.fillWindow(ILI9341_BLACK);
  tft.fillRect(30, 120, 100, 65,ILI9341_YELLOW);
  tft.fillRect(100, 170, 120,60,ILI9341_BLUE);
  //tft.updateScreen();
  tft.color565toRGB(tft.readPixel(65,150), r, g, b);
  Serial.println(tft.readPixel(65,150));
  Serial.println(r);
  Serial.println(g);
  Serial.println(b);

  uint16_t awColors[240];
  tft.readRect(0, 172, 240, 1, awColors);
  for(int16_t j = 0; j < 240; j++) {
    tft.color565toRGB(awColors[j], r, g, b);
    Serial.printf("%d, %d, %d, %d\n", j, r, g, b);
   }

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

You might give it a try for the ILI9488

**Comment by KrisKasprzak** [comment]
Rats... It tried this using the ILI9488_t3 lib and while it returns a color, the color is random. I tried slowing the bus speed down but no luck. 

My goals are
1. have a working display
2. able to read a pixel
3. able to write to SD card
4. able to use touch

I can do all these on the 9341, but would like to use larger displays. Any further assistance is greatly appreciated.

Kris

**Comment by mjs513** [comment]
Not sure you are going to like this answer.  Looks like for the ILI9488 you are going to have to use frame buffer to use read pixel.  I just tried the original sketch and even with slowing down the read clock to 20MHZ didn't work.  Maybe if you slow it down even more it would work.

this worked though
```
#include <ILI9488_t3.h>
//#define TFT_DC  9
//#define TFT_CS 10
//#define TFT_RST 8
//ILI9488_t3n tft = ILI9488_t3n(TFT_CS, TFT_DC, TFT_RST);

#define TFT_DC  9
#define TFT_CS 10
#define TFT_RST 8
#define TOUCH_CS 27
ILI9488_t3 tft = ILI9488_t3(TFT_CS, TFT_DC, TFT_RST);

void setup() {
  pinMode(TOUCH_CS, OUTPUT);
  digitalWrite(TOUCH_CS, HIGH);

  delay(100);
  tft.begin();
  tft.fillScreen(ILI9488_BLACK);

  tft.setTextColor(ILI9488_WHITE);
  tft.setTextSize(2);
  tft.println(F("Waiting for Arduino Serial Monitor..."));
  while (!Serial) {
    if (millis() > 3000) break;
  }
  Serial.printf("\nScreen Width: %u Height: %d\n", tft.width(), tft.height());

  uint8_t r, g, b;
  tft.useFrameBuffer(true);
  //tft.fillWindow(ILI9488_RED);
  tft.fillScreen(ILI9488_BLACK);
  tft.fillRect(30, 120, 100, 65,ILI9488_YELLOW);
  tft.fillRect(100, 170, 120,60,ILI9488_BLUE);
  tft.updateScreen();
  tft.color565toRGB(tft.readPixel(65,150), r, g, b);
  Serial.println(tft.readPixel(65,150));
  Serial.println(r);
  Serial.println(g);
  Serial.println(b);

  uint16_t awColors[240];
  tft.readRect(0, 172, 240, 1, awColors);
  for(int16_t j = 0; j < 240; j++) {
    tft.color565toRGB(awColors[j], r, g, b);
    Serial.printf("%d, %d, %d, %d\n", j, r, g, b);
   }

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by KrisKasprzak** [comment]
My dearest Mike S. You are a super genius!

The use of frame buffer works! I guess the only drawback is performance when having to draw data one-bye-one, updateScreen seems to pop every thing very quickly.

At any rate I now have 
1) display, 2) PrintScreen 3) SD functions, 4) and touch.

Bingo!

**Comment by mjs513** [comment]
If you get it working I can give it a try.  Assume you are using BMP's
[ILI9341_BUDDHABROT_PNG.zip](https://github.com/mjs513/ILI9488_t3/files/9648319/ILI9341_BUDDHABROT_PNG.zip)
Here is a way to do PNGs and use MTP but its on a ILI9341 - not 100% sure it still works :)

**Comment by KrisKasprzak** [comment]
Thanks i'll look at the above. In the meantime, have a look at PrintScreen for the ILI9488 :) I recommend using the ILI9488_t3_PrintScreen_SdFat.h (based on SdFat)

https://github.com/KrisKasprzak/ILI9488_t3_PrintScreen

**Comment by KrisKasprzak** [comment]
From the notes, I will change my open to use FILE_WRITE_BEGIN
